### ISSUE TITLE
Clear Response History command for entire workspace

### ISSUE THREAD

**Issue by fredrikhr** [AnWeber/vscode-httpyac#108]
Currently the Clear Response History command only clears the history for the currently open file.

It would be useful if we could clear the response history for the entire workspace. 

I propse one of the following actions:

* Modify the existing Clear Response History command to act on the entire workspace  
   see https://github.com/AnWeber/vscode-httpyac/compare/main...fredrikhr:clear-history-all-files?expand=1
* Add a new command to clear the response History for the entire workspace and leave the existing command as it is.  
   I'd recommend that the current open-file-only clearing command gets a different Text with the suffix `(this file)` to make it clear in the UI that the command only operates on the current file.

**Comment by AnWeber** [comment]
The 2nd idea with (current file) does not fit me, since I delete the history of all files. But the first one does not fit either. 

My problem is that for me I can not currently describe the two commands `httpyac.reset` and `httpyac.clearHistory` in words.

Currently reset clears the documentStore and the userSessionStore. If I modify existing Clear Response History command I would clear responseStore and documentStore (clearAll or iterate over all files and delete response/variables is more or less the same, just some reparsing). 
Presumably the responseStore should also be deleted during reset. And the userSessionStore is the difference. Logins and cookies remain, only the variables and responses do not. Do you have an opinion on this subject?

**Comment by fredrikhr** [comment]
Hmm... So here's an example of a scenario I have:

Use case SharePoint. Within a tenant you one SharePoint server instance (`https://{tenantName}.sharepoint.com/`) and then you have multiple site collections underneath that (e.g. `/sites/a`, `/sites/b`, etc.). Each SiteCollection has its own API route, but the API functionality is the same.

So for general purpose access to SharePoint site collections, I have a folder with a `.site.http` file. In there I use a script region, use `userInteractionProvider` to prompt the actual site path I want to use and export the result as a variable. Then all my other http files `@import` and `@ref` that region making them "site-agnostic".

So what I need is a way to invalidate the site-choosing region, and then invalidate all other regions that depend on that. Currently I actually need to reload VS Code or call reset on each file individually.

In this case I actually don't want to clear the `userSessionStore`, I just need to clear stored variables. So I guess the actual use-case is that `@import` generates a dependency tree. That would also be useful to detect cyclic dependencies. But that means re-working the `@import` directive

**Comment by AnWeber** [comment]
Yes, a real dependency tree would be better. I have currently implemented an economy variant.
I think I implement it as described before. `removeHistory` deletes the responseStore and the documentStore (resposne + all variables). `reset` does everything. Then I'll get your use case too.

**Comment by AnWeber** [comment]
I have now published the change with v5.2.0
