### ISSUE TITLE
Response preview editor window does not use region `@name` as tab title

### ISSUE THREAD

**Issue by fredrikhr** [AnWeber/vscode-httpyac#114]
The editor tab that VS Code opens to display the response is titled according to the end of the URL and does not take the `@name` directive on the executed region into account.

This leads to some of my requests having weird file extensions in cases when the last part of the URL is a `{{object.property.expression}}`. The weird file ending leads VS Code to syntax highlight the response as plaintext even if I get a JSON response with the header specifying `application/json`.

Could we at least special case json and xml responses to have `.json` or `.xml` suffixes in the response editor tab so that VS Code has less reason to get confused?

`vscode-httpyac`: `v5.2.2`

**Comment by fredrikhr** [comment]
I have a request to the SharePoint API that looks similar to this:

```http
###
# @name ListV2
# @ref ListCollectionV2PickOne
GET {{ContextInfo.WebFullUrl}}/{{SharePointApiV2Path}}
  /sites/~web
  /lists
  /{{ListCollectionV2PickOne.id}}
  ?$select=*,sharepointIds
Authorization: oauth2 {{sharepoint_grantType}} sharepoint
OData-Version: 4.01

```

which results in the editor tab named `api_sites_~web_lists_$select=_,sharepointIds.id}}`, i.e. it takes the literal value of the URL before replacing variables as the path and infers the extension from the last `.` in the URL filename, in this case `.id}}` from `{{ListCollectionV2PickOne.id}}` which is an object property dereferencing expression and thus contains a `.`.

If I set `responseViewExtensionRecognition` to `mimeType` the response is correctly highlighted as JSON by virtue of SharePoint returning `Content-Type: application/json` in the response. It still leads to the very interesting (but maybe acceptable) file name of `api_sites_~web_lists_$select=_,sharepointIds.json`.

**Comment by AnWeber** [comment]
great name, `api_sites_~web_lists_$select=_,sharepointIds.json`. Love it:-) I fixed the bug with short variable names with the first commit (`api_sites_~web_lists_$select=_,sharepointIds.id}}`)

Do you have a suggestion how I can best determine unique filenames. If I want to use the preview in VSCode, I have to save the response as a file, otherwise the preview does not work correctly. However, the user can edit the file at any time and thus the file remains open for further requests. Therefore, the file name must be unique. I could use a GUID or `response-{number}}`. Using the url path is used is only to make it easier to find the response again. Do you possibly have a better idea how I can get a good name?

**Comment by fredrikhr** [comment]
Hmm, doesn't VS Code have virtual buffers? IIRC the C# extension can show a decompiled view of function declarations from a native assembly (when you hit "Go to definition" on an API that is in a compiled assembly). To my knowledge when OmniSharp does that it does not actually produce the file, but only shows a virtual read-only buffer in VS Code that exists only in memory.

**Comment by AnWeber** [comment]
The Virtual Buffers would mean that I would have to register my own [TextDocumentContentProvider](https://github.com/OmniSharp/omnisharp-vscode/blob/27d6566d73623d8e168dbc4978433e4e479f4cde/src/features/definitionMetadataDocumentProvider.ts#L48). But I would still have the problem with the url. I think that doesn't improve anything, since I save the response to the hard disk to save memory.
With the last version I have already implemented the use of the `# @name` as filename.
