### ISSUE TITLE
Show request body in md file

### ISSUE THREAD

**Issue by gerukin** [AnWeber/vscode-httpyac#120]
Clicking on the codelens for a json response opens an md file with information about the request, the response, and meta data. It doesn't include the request's body however (while it is included in the CLI's default output). It would be very helpful to see the actually send body directly in vs-code.

**Comment by AnWeber** [comment]
I'm torn. The change was intentional because I added the history feature and I wanted to save memory by deleting the [`request.body`](https://github.com/AnWeber/vscode-httpyac/blob/main/src/responseStore.ts#L121) (I upload PDF).
You would also see the request.body in the Output Channel Log. This contains the same display as the CLI. Is this sufficient for you as well?
<img width="961" alt="image" src="https://user-images.githubusercontent.com/13434739/162045462-fa58df13-552a-4b06-8943-c6c2058145fd.png">

**Comment by gerukin** [comment]
Hmmm, thanks for the explanation. It's enough and yes, I could just look at that. Not as easy to quickly check, or save & share (the `md` file has more or less everything in one nice format)... but still sufficient for debugging purposes indeed.

I suppose the memory issue is present for both the request and the response right?

Maybe you could always show the body in the `md` file, but have a new setting like `httpyac.maxBodySize` to not save bodies in the history (request or response) if the size is over a given limit. And maybe only show bodies over this limit in the current request's `md` file after clicking a new button to _force reveal_ it?

**Comment by AnWeber** [comment]
> I suppose the memory issue is present for both the request and the response right?

Yes, I save the body of the response in a folder, and make sure to empty it correctly and also reload the body into memory if necessary. But for the request body it's almost not worth the effort for me, because these are probably rather small. For this reason I have now only created a way to keep the request body in memory. Just use the new setting `httpyac.responseViewPrettyPrint` that will be included in the next release (0 = keep complete body, otherwise only the given size).

**Comment by AnWeber** [comment]
Change is released with the v5.4.0.
