### ISSUE TITLE
Erroneous syntax highlighting for JSON body non string variables

### ISSUE THREAD

**Issue by gerukin** [AnWeber/vscode-httpyac#123]
Writing this:
```
POST https://ohnoiwillfa.il
Content-Type: application/json

{
  "num": {{$randomInt 0 10}},
  "str": "{{$randomInt 0 10}}"
}
```

Gives you a more colorful result than expected:
<img width="240" alt="oh noooo" src="https://user-images.githubusercontent.com/36127103/163313823-341cd29c-019f-4384-9167-6186c8084dbe.png">

**Comment by AnWeber** [comment]
I currently made it easy for myself and do not implement the JSON highlighting myself, but directly use the [JSON syntax of VSCode](https://github.com/AnWeber/vscode-httpyac/blob/main/syntaxes/http.tmLanguage.json#L62). It would mean [following rules to extend templating and use as new syntax like `httpJSON`](https://github.com/microsoft/vscode/blob/main/extensions/json/syntaxes/JSON.tmLanguage.json). The content in the template would again probably be javascript, Intellij Replacer or ..... There are many options that currently do not use proper syntax highlighting.. It kind of falls under LSP for me, since I would probably have to improve the current parsing of the text file then as well. Currently I parse per line. But for better support I would really need more token based.

**Comment by AnWeber** [comment]
In the end, I still halfway understood how it works. Textmate syntax is definitely not fun for me. It was kind of tricky to figure out why I need an injection into my own language for overwriting the `source.json` styles. But this is how it worked. It took me several attempts. I did some additional optimizations now and hopefully I can just displace the knowledge again.  I have released a new version.
