### ISSUE TITLE
Show variable content on mouse hover

### ISSUE THREAD

**Issue by bugybunny** [AnWeber/vscode-httpyac#132]
![image](https://user-images.githubusercontent.com/5311105/173050554-6a17fe6d-85a9-4dd3-99b9-e9df5b644f7c.png)
I would like to see the value `https://myservice.com` in the mouse over on usage in the .http file. 

This extension e.g. https://github.com/Huachao/vscode-restclient shows it like this and I would also like to see this in vscode-httpyac
![image](https://user-images.githubusercontent.com/5311105/173051839-453b0d14-4fde-463e-a473-29c995e9ec77.png)

**Comment by AnWeber** [comment]
I am not yet a fan of the display at `mouseover`. Reason is actually exactly the way of implementation in `vscode-restclient`. This causes some performance problems and has caused me some headaches when implementing the PR #521 Script Code Evaluation for variables. 
For simple variables from the environment settings it would still be conceivable, but these are actually static and can also be looked up in the sidebar. 
For variables from JavaScript area for which it would be really helpful, however, it becomes more interesting. I have very consciously decided against running the JavaScript without user interaction. Exactly for performance reasons and on the other hand also, because in the script area everything can happen (file create, database queries). Because the control is missing here, the determination of the value is not easily possible.
Another problem is my not ideal implementation of the parser. I decided in the beginning to recognize the evaluation of the variables only at runtime. So I don't know the position of the variables in the text. There would be still some optimization effort and one could consider to support the Language Server Protocol in the same course.
I'll think about how complex it really is. But if you're interested, you're welcome to try to create a PR.

**Comment by bugybunny** [comment]
> For simple variables from the environment settings it would still be conceivable, but these are actually static and can also be looked up in the sidebar.

Then I would like to just see this and I request this with this issue, that's completely fine for my usage. I know that the static variables can be seen in the sidebar. However, the sidebar is just practical for a small number of variables as e.g. the variables cannot be sorted (have a fixed sorting, most likely the order they have been declared) or filtered. So not really practical if you have many variables. But this topic of the sidebar would be another feature request.

So I would like to see the static variable values in the mouse hover.

**Comment by AnWeber** [comment]
I have now added a HoverProvider for variables. This uses the variables of the last request or if not yet available the current environment variables for the display. I have just published the change.
