### ISSUE TITLE
Httpyac tests in Vscode Test Explorer

### ISSUE THREAD

**Issue by BramManuel** [AnWeber/vscode-httpyac#140]
I have been using vscode-httpyac for a while now, and I love it!
But there is one thing I miss, and that's running my tests, the CLI supports running test and also the httpbook supports it.

I would like to use the native VS Code test explorer to run all of my httpyac tests.

PR is on its way 😉

**Comment by li1234yun** [comment]
Hello!
It's good idea! This is my some advices:

- If the test icon is always show will be better when I write new http request.

<img width="880" alt="image" src="https://user-images.githubusercontent.com/26505658/182006838-b38fbd95-2654-461a-a776-f9e94d79407f.png">

- Test explore may have other language result, such as `go`/`python`. Maybe `http` tests can be in a directory.

**Comment by AnWeber** [comment]
@li1234yun 
> If the test icon is always show will be better when I write new http request.

Yes I would have planned for the test icon to appear immediately when changes are made to a file. The necessary event registrations are still missing in the current state. I have broken the implementation of BramManual. I would have also built in the special case that when executing a test it behaves like when you press the CodeLens (directly show response in separate editor)

> Test explore may have other language result, such as go/python. Maybe http tests can be in a directory.

Do you mean that the root folder should be something like `httpyac Test Provider`? I would have used the folder structure of the workspace directly. Similar to [Jest Extension](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest). [Go Extension](https://github.com/golang/vscode-go/blob/78c2fac416c4a18c5741ee25a6c4c17074673275/src/goTest/utils.ts#L24) or [Java Test Runner](https://github.com/microsoft/vscode-java-test/blob/main/src/controller/testController.ts#L54-L66) uses a language specific representation (packages, modules). Do you have a good idea, how to create a useful folder structure? The idea that I use information from `.http` files, I have discarded, because in large projects the performance suffers.

**Comment by li1234yun** [comment]
Hello @AnWeber 

> Do you mean that the root folder should be something like httpyac Test Provider?

Yes, becasue same workspace maybe exists multiple tests result, such as Go/Python etc. It will be better in one folder.

> Do you have a good idea, how to create a useful folder structure?

![image](https://user-images.githubusercontent.com/26505658/182053532-d2e6813c-c038-4adb-98a0-526d8791289a.png)
![image](https://user-images.githubusercontent.com/26505658/182053581-4196aedb-fa13-4886-9464-7104506930b1.png)

Python use the project file layout.

![image](https://user-images.githubusercontent.com/26505658/182053631-dbdd47a8-03bf-4cc0-8779-14c3c9ae9b6c.png)
![image](https://user-images.githubusercontent.com/26505658/182053718-59f9c6b8-fb56-474e-aeed-5c882a2a3b96.png)

Go use package module name and test file name.

AnWeber, you can refer them.  I think `I would have used the folder structure of the workspace directly.` is fine.

**Comment by BramManuel** [comment]
@AnWeber Do you have an idea when this will be released? 
Thanks for all the refactoring, I learned allot from it 👍

**Comment by AnWeber** [comment]
@BramManuel Sorry that it takes longer. I stumbled across https://github.com/microsoft/vscode/issues/156925 and still had thought about using FileSystemWatcher and added more and more features. I will publish it the next days. I try today. Just one more small feature:-)

**Comment by AnWeber** [comment]
I have published the test controller support. Please test once and more suggestions. And thanks again for the PR @BramManuel
