### ISSUE TITLE
updates to any external file imported using "require" are ignored

### ISSUE THREAD

**Issue by nimatrueway** [AnWeber/vscode-httpyac#142]
# Reproduction Steps

1. Create a `rest` file, and a lib file as follows:

**httpyac-sample.rest**
```
{{
  const { endpoint } = require('./httpyac-sample-lib')
  exports.endpoint = endpoint
}}

GET https://yesno.wtf/{{endpoint}}
```

**httpyac-sample-lib.js**
```
exports.endpoint = "api"
```

2. Run the request in **vscode** using **httpyac** plugin.
3. Now change the lib file.

**httpyac-sample-lib.js**
```
exports.endpoint = "XXX"
```

4. Re-run the request.
5. The changes made to the lib file are ignored. In other words, the variable `endpoint` still has the `"api"` value.

**Comment by AnWeber** [comment]
The behavior is a default behavior of NodeJS. NodeJS [caches all loaded require modules](https://nodejs.org/api/modules.html#caching). The following workarounds are available

- This cache can still be cleared when using CommonJS, but not when using esm. For that reason, I currently have a [`requireUncached`](https://github.com/AnWeber/httpyac/blob/5e15b93e8a113638fd6e5c6c919dec8476b416e7/src/plugins/javascript/moduleUtils.ts#L110) method provided, but not documented, since I actually want to switch to esm. Currently VSCode does not support esm yet.
- My preferred way is to write scripts in the http file first and dump them to javascript files only at the end. For changing variables I always use `.env` files
- VSCode supports restarting the extension host (command workbench.action.restartExtensionHost). This will load all extensions in a new NodeJS environment and also flush the NodeJS cache

**Comment by nimatrueway** [comment]
Thanks a lot @AnWeber for the thorough explanation! I was using method #2 and #3 as you described but had no idea about method #1. Sounds like a great workaround, I hope that you can keep it in the project it's very useful.

**Comment by AnWeber** [comment]
@nimatrueway As long as I use CommonJS, the method remains. After switching to esm I will look, but currently there is no workaround for the problem. And esm not going to come anytime soon, so feel free to use it.
