### ISSUE TITLE
Syntax highlighting in Markdown

### ISSUE THREAD

**Issue by QuAzI** [AnWeber/vscode-httpyac#149]
Please add syntax highlighting to markdown.
Only `send` button presents at the moment

![image](https://user-images.githubusercontent.com/1897605/189585199-ac634f02-f47e-4637-9d75-d832bddd059c.png)

**Comment by AnWeber** [comment]
Syntax highlighting in Markdown is added with v5.7.1. So you found the sources:-) Thx for using my app

**Comment by QuAzI** [comment]
Yeah! Amazing app. I hope it can be helpful even for autotests.
But MD a bit unfinished because right part still not highlighted
![image](https://user-images.githubusercontent.com/1897605/189744199-9ce14a51-e45d-490c-8e23-4bada8f3706b.png)

**Comment by AnWeber** [comment]
@QuAzI This is automatically generated from the Markdown by `markdown-it`. I thought that there is no interface for this on the part of VSCode, since this is not mentioned in the VSCode API. But this is not quite correct, as it is described on a separate page ([Adding support for new syntax with markdown-it plugins](https://code.visualstudio.com/api/extension-guides/markdown-extension#adding-support-for-new-syntax-with-markdownit-plugins)). I must confess, however, that I don't currently have much time to familiarize myself with the `markdown-it` api to provide a complete syntax highlighting. Maybe the extension [davidmwhynot.markdown-higlightjs](https://marketplace.visualstudio.com/items?itemName=davidmwhynot.markdown-higlightjs) or [bierner.markdown-prism](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-prism) will help you, it offers limited syntax highlighting. Prism is used on httpyac.github.io

<img width="427" alt="image" src="https://user-images.githubusercontent.com/13434739/189981504-b837ee8d-b552-4c7c-8c3c-c31850858fd3.png">

PR are also gladly accepted. Basically you have to convert the `http.tmLanguage.json` into a markdown-it API.
