### ISSUE TITLE
"Cannot set headers after they are sent to the client" when sending multipart/form-data POST request

### ISSUE THREAD

**Issue by wurmser-f** [AnWeber/vscode-httpyac#156]
Hello,

I cannot seem to be able to send multipart/form-data POST requests, I always hit the following error :

"Cannot set headers after they are sent to the client"

All other requests work fine.

**Comment by AnWeber** [comment]
I think that is not a mistake in my extension. [My example for multipart-formdata](https://httpyac.github.io/guide/request.html#multipart-form-data) still works correctly. Additionally, this is actually an error that is reported by the server rather than generated by the client. I know it using express.js (https://stackoverflow.com/questions/7042340/error-cant-set-headers-after-they-are-sent-to-the-client)
If you still think it's a client-side error, I'd need an example of how to trigger that.
