### ISSUE TITLE
Error bubles when the request successfully completed

### ISSUE THREAD

**Issue by dypa** [AnWeber/vscode-httpyac#18]
Build 1.16.0

Test case:
```
###First request
GET https://httpbin.org/get?test={{test}}

###Second request
GET https://httpbin.org/get?test={{$randomInt}}
```

Actual result:
Steps:
1. Run "First request" and see error buble "ReferenceError: test is not defined at Object.userJS" and no response window.
2. Run "Second request". Error buble hides and show request process. When request finished i see error buble  "ReferenceError: test is not defined at Object.userJS" and correct response window.

![Peek 2021-03-01 11-58](https://user-images.githubusercontent.com/80477/109474367-7d846600-7a85-11eb-82c0-421212d985df.gif)

Expected result:
Run "Second request" not bubles error

**Comment by AnWeber** [comment]
I can understand the behavior. But this is the default behavior of VS Code. If there is not enough space in the height. it hides the info window for a short time. If there is even less space, it even hides all windows. 
![vscode](https://user-images.githubusercontent.com/13434739/109702604-bceda800-7b94-11eb-8f5c-6d22b235a7da.gif)

VS Code does not offer me the possibility to close the error window automatically, nor the possibility to set a timer. 
There is even an issues ([2732](https://github.com/Microsoft/vscode/issues/2732) or [51013](https://github.com/microsoft/vscode/issues/51013)) for this case, but I didn't want to implement the workaround with statusbar message. 
I can only offer a setting so that I no longer display any notifications

**Comment by AnWeber** [comment]
in current release 1.17.0 you can disable notifications.

**Comment by AnWeber** [comment]
Closing the Issue. I have no further idea how to improve the behavior with the current version of the VS Code Api. If you have any questions just contact me again.

**Comment by dypa** [comment]
build: 1.17.0
now looks as expected, i see two different bubbles now
