### ISSUE TITLE
automatically set default env in a project without manually selecting

### ISSUE THREAD

**Issue by domeniczz** [AnWeber/vscode-httpyac#192]
there could be a feature that set the env to default if there's only one env config.

for example in the config `http-client.env.json` below, there is only one env defined, so the plugin can be smart enough to set `dev` as default env

```json
{
  "dev": {
    // ...
  }
}
```

**Comment by AnWeber** [comment]
I do not find the feature useful. No environment is a valid environment for me (my default with local settings). Another point is that I want to minimize resource usage. I would have provided different alternatives that also achieve your desired behavior.

- use setting `httpyac.environmentSelectedOnStart` 
- use `.env` instead of Intellij Config Files 
- add a [custom plugin using `.httpyac.js` which automatically sets your default environment](https://httpyac.github.io/config/#configurehooks), if it is not set

```js
module.exports = {
	configureHooks: function (api) {
		api.hooks.parseEnd.addHook('set_env', function (context) {
			if (!context.httpFile.activeEnvironment || context.httpFile.activeEnvironment.length === 0) {
				context.httpFile.activeEnvironment = ['dev']
			}
		});
	}
}
```
