### ISSUE TITLE
httpyac.responseViewLanguageMap not works

### ISSUE THREAD

**Issue by IRuzhnikov** [AnWeber/vscode-httpyac#193]
Hi!
i was try use it like (for pretty print in preview)
```json
"httpyac.responseViewLanguageMap": {
    "application/json-rpc": "json"
},
```
and when I opened sourcecode i fount strange strings
```javascript
function getExtensionByMimeTypes(response: httpyac.HttpResponse) {
  if (response?.contentType?.contentType) {
    return extension(response?.contentType?.contentType);
  }
  return false;
}
```
but in a same time another functions used just one chain call to contentType
```javascript
function getExtensionByRegexMimetype(response: httpyac.HttpResponse): string | false {
  if (response?.contentType) {
    const contentType = response?.contentType;
    if (httpyac.utils.isMimeTypeJSON(contentType)) {
      return 'json';
    }
   //....
}
```

Permalink to original code:
https://github.com/AnWeber/vscode-httpyac/blob/c8c37e4658715282cf2bf286829ed981f736e81c/src/view/responseItem.ts#L141

Thanks!

**Comment by AnWeber** [comment]
To use the preview mode in VSCode, the response must be saved as a file. The display language is determined by the file extension. Because of this I had the problem that I do not know the file extension for a LanguageId. My way is to save the most common LanguageId with the correct file extension, but if necessary to set the LanguageId active when opening the response, if it is available in the map.
