### ISSUE TITLE
Code completion deletes some characters

### ISSUE THREAD

**Issue by bohni** [AnWeber/vscode-httpyac#224]
`@variable={{$pa` + \<tab> gives `@variable={{$ssword`

`?? stat` + selecting entry "?? status == 200" + \<enter> gives `?? tatus == 200`

**Comment by AnWeber** [comment]
I have to admit, I don't get what Microsoft wants from me with the Completion API. It seems that I am not allowed to specify special characters in the insertText, but I have to specify normal characters so that they are replaced correctly. This behaves extremely strange. I think it works correctly now, but please test it. 

| input | insertText |
| - | - |
| `{{$pa` | `password` |
| `?? stat` | ` status == 200` |
| `??` | `?? status == 200` |
| `Con` | `tent-Type` |
```
I also tweaked the performance, and the CompletionItems should appear faster.
