### ISSUE TITLE
setup response path/ clear up response files

### ISSUE THREAD

**Issue by Med-H** [AnWeber/vscode-httpyac#241]
httpyacc is storing responses under **.../Code/User/globalStorage/anweber.vscode-httpyac/_httpyac_/**

can you please add an option to setup the path to the reponse folder, and maybe the option to clean it up?

keep up the good work and thank you in advance.

**Comment by AnWeber** [comment]
Command `httpyac.pruneStorage` cleans the storage. This simply deletes the entire folder. This is also the reason why I find it so difficult to make it configurable. I don't want to accidentally delete the wrong files. That's why I would have created an extra command for the output of files in the current folder. see [output-redirection](http://localhost:5173/guide/response.html#output-redirection)

**Comment by jayYoung888** [comment]
There seems to be no way to access your link

**Comment by AnWeber** [comment]
I have now added several configuration options.
- global (behavior as before)
- workspace (storage within the workspace)
- file (storage next to the current file)
- none (no caching in filesystem)

I can't seem to clean up the files when closing vscode. I can't get vscode to close. And during the dispose, filesystem API access is no longer possible (open issue at VSCode). For this reason there is now only the manual option to delete the files.

**Comment by Med-H** [comment]
> I have now added several configuration options.
> 
> * global (behavior as before)
> * workspace (storage within the workspace)
> * file (storage next to the current file)
> * none (no caching in filesystem)
> 
> I can't seem to clean up the files when closing vscode. I can't get vscode to close. And during the dispose, filesystem API access is no longer possible (open issue at VSCode). For this reason there is now only the manual option to delete the files.

great job m8
