### ISSUE TITLE
Wrong request host

### ISSUE THREAD

**Issue by maicss** [AnWeber/vscode-httpyac#242]
```http
GET http://localhost:3000/api/hello-world
```
When click to execute it, gives an error:
```
connect ECONNREFUSED 127.0.0.1:3000
```

Environment:
follow https://nuxt.com/docs/getting-started/installation#development-server, create a folder in server named `api`, and a js file name `hello-world`

When I change `package.json -> scripts -> dev -> nuxt dev` to `package.json -> scripts -> dev -> nuxt dev --host`, request success.

Expectation: request to localhost not 127.0.0.1

**Comment by AnWeber** [comment]
@maicss It is a NodeJS issue but I have no solution at the moment. I will link some docs

**Comment by maicss** [comment]
Wow, Thank you, can you update this limit to readme? That will helps other who have the same problem.

**Comment by AnWeber** [comment]
@maicss I'm just not 100% sure how the error is triggered. I have only seen similar errors in rest-client and postman issue log. I think it is internally related to DNS. In the debuggable code the host was still localhost. Either it is internal to NodeJS or at the DNS level. But since it affects different systems, I tend to NodeJS. But all without guarantee
