### ISSUE TITLE
File seems to be binary and cannot be opened as text - Error from vscode for zip file

### ISSUE THREAD

**Issue by alan-francis** [AnWeber/vscode-httpyac#276]
When trying to emit a .zip file from a POST method, encounter the following error.
`cannot open vscode-remote://wsl%2Bubuntu/home/alan/.vscode-server/data/User/globalStorage/anweber.vscode-httpyac/.httpyac/http_0.0.0.0_8088_orchestrate.zip.73246235.zip. Detail: File seems to be binary and cannot be opened as text`

**Comment by AnWeber** [comment]
Hi, yes I understand your problem, but it was more or less a design decision. Extensions can register any files in vscode and extend the functionality. For example, there is [a viewer for the zip display](https://marketplace.visualstudio.com/items?itemName=AdamRaichu.zip-viewer) . However, I cannot see whether a corresponding viewer is installed and activated (no API).
I am now taking an optimistic approach. I always try to open and display the file. But because I don't notice any errors due to the lack of an API, I think it's the user's responsibility to tell httpyac if an error occurs. This is possible with [`# @save`](https://httpyac.github.io/guide/metaData.html#save) or [`# @openWith`](https://httpyac.github.io/guide/metaData.html#openwith)

Does that help you? Suggestions for improvement?

**Comment by greenbigfrog** [comment]
I'm not sure this is truly completed.

I'm using `>>! file.tif` to redirect output to a file. I do not want to open the file within VSC in any case.
`# @save` prompts for where to save the response, which I already configured with the redirect.

A possible solution I can imagine would be changing `# @openWith` to support `null` or `not` to not open it at all (or perhaps a empty `openWith` could also work).
