### ISSUE TITLE
Executed twice of one region

### ISSUE THREAD

**Issue by slackwareer** [AnWeber/vscode-httpyac#280]
A region with only JavaScript code(has no request) executed twice.

```js
{{+
    console.log('A');
}}

### 1
{{
    console.log('B');
}}
```
When region1 is executed ,it print two `B`.

![image](https://github.com/AnWeber/vscode-httpyac/assets/239952/cff74949-83ec-48a3-a684-6d3ac6be1f27)
It's confusing me so mush....

**Comment by AnWeber** [comment]
The mistake is funny. When parsing, I assign the same Id `js` to both scripts. The initial thought was that nobody has the same element in a range. However, the `+` pushes it into the same processing chain. Actually no problem, because I actually make sure that they still have a unique idea, except for this case. Too bad. Both end up in a map with the same ID and the second script overwrites the first. Fixed by forcing a unique id in this case as well.

**Comment by slackwareer** [comment]
> The mistake is funny. When parsing, I assign the same Id `js` to both scripts. The initial thought was that nobody has the same element in a range. However, the `+` pushes it into the same processing chain. Actually no problem, because I actually make sure that they still have a unique idea, except for this case. Too bad. Both end up in a map with the same ID and the second script overwrites the first. Fixed by forcing a unique id in this case as well.

Appreciate for you efficiency    o(￣▽￣)ｄ
