### ISSUE TITLE
Test results show test descriptions instead of names

### ISSUE THREAD

**Issue by alekdavis** [AnWeber/vscode-httpyac#318]
I'm not sure if this is intentional, but I just noticed that test results show the description in the beginning of the request block. IMHO, it would be more appropriate to display the name (description could be displayed optionally based on the settings, if at all). Example:

![image](https://github.com/user-attachments/assets/ae14a32f-9276-4a0f-b537-b657b8f616af)

I think it would make more sense to have `Demo test one` at the top of the TEST RESULTS output instead of `Test with no dependencies.`.

**Comment by AnWeber** [comment]
Actually, it would be title before description. For me, title is not quite the same as name. Unfortunately, I used name for referencing (identifier would have been better). As a result, the name is somehow technically required. That's why I introduced another title, which is used for the display. I also use the name as a fallback instead of title. However, this also affects the changed behavior in the CLI

https://github.com/AnWeber/httpyac/blob/main/src/utils/requestUtils.ts#L207-L214

**Comment by alekdavis** [comment]
Right, I actually meant the title (I assume the text to the right of the region delimiter `###` is the title and it is a shortcut for `# @title`). And you're right, the `id` would be less ambiguous, but name/title/description also make sense.
