### ISSUE TITLE
Mask passwords in output

### ISSUE THREAD

**Issue by kobmik** [AnWeber/vscode-httpyac#324]
When I run the following example, the query parameters including the password will be visible in the output window.

@pwd={{$password Password}}
GET https://www.abc.xyz/test?password={{pwd}}

Is there a way to mask the password variable in the output?

Same problem with environment variables. Is there even a way to mark env variables as secrets?

**Comment by AnWeber** [comment]
@kobmik  The problem is that I cannot recognize where passwords or secrets are displayed due to the integration of Javascript. In my life I have seen all variants (header, custom header, query params or in the payload). In other words, I have decided not to solve the problem at all and only provide an API (responseLogging Hook) that allows you to remove the passwords yourself before the output.

https://github.com/httpyac/httpyac.github.io/blob/main/examples/plugins/responseLoggingHook/httpyac-plugin-example/index.js#L2

**Comment by AnWeber** [comment]
If you have any suggestions as to what I could usefully implement, please let me know.
