### ISSUE TITLE
External scripts not updated

### ISSUE THREAD

**Issue by gerukin** [AnWeber/vscode-httpyac#53]
External scripts seem to be cached and require restarting vscode to run the updated code.

## Example
```
# in request.http
{{
  // ...
  require('external.js').is({ test, response })
}}
```
```javascript
// external.js
// ...

module.exports.is = ({ test, response }) => {
  test('Test name', function () {
    // ...
  })
}
```
```javascript
// external.js - after some edits
// ...
  test("Test name - I was just edited yet this won't show", function () {
// ...
```

Hitting `send` from vscode the first time will show `Test name`. Hitting `send` after the edit will still show `Test name`. Restarting vscode is enough to see the updated code right away. The script in `request.http` itself is always updated right away (no caching? - no restart needed).

## Bonus :)
```javascript
// external.js
console.log('Good luck making me show in the ScriptConsole - ever')
```
```
# in request.http
console.log('I always show just fine 🎉')
```

The CLI shows all console logs.

**Comment by AnWeber** [comment]
Cause is the [caching of Node JS](https://nodejs.org/api/modules.html#modules_require_cache). The code is executed in the context of the VSCode Extension Host and as long as it is active, all scripts are cached. Currently there is the possibility to simply restart the extension host (command in VSCode) , or to delete them manually from the cache using the following script.
```
# in request.http
{{
  delete require.cache[require.resolve('./external.js')]
  require('external.js').is({ test, response })
}}
```
I'll have a look at jest, since there seems to have been a [better solution found (jest.resetModules)](https://stackoverflow.com/questions/9210542/node-js-require-cache-possible-to-invalidate). I have created my scripts with the help of the cli app, which gets restarted after every call.

### Bonus :)
For the inline scripts I create a separate module, where I redirect the [console calls to a separate object](https://github.com/AnWeber/httpyac/blob/main/src/actions/javascriptAction.ts#L46). With require loaded scripts, this is hard to do without rebuilding the complete require logic of NodeJS (maybe jest developer have some better ideas I can copy). The second option would be to [redirect process.stdout](https://stackoverflow.com/questions/32719923/redirecting-stdout-to-file-nodejs), but I would also intercept logging from other extensions, which I don't want. I would currently simply recommend passing the console object.

**Comment by AnWeber** [comment]
good read: discussion of caching of require calls in context of vscode (https://github.com/microsoft/vscode/issues/84588)
I'm on the right track, I probably just need to play with the NodeJS Api

**Comment by AnWeber** [comment]
My plan now would be not to automatically bypass the behavior. This is standard in NodeJS and there are good reasons for it. Instead I provide a helper method `requireUncached` that automatically clears the cache.

**Comment by AnWeber** [comment]
I have provided a new version 3.0.0 where this method `requireUncached` is usable
