### ISSUE TITLE
GRPC Call support

### ISSUE THREAD

**Issue by zesagata** [AnWeber/vscode-httpyac#62]
Is there any future plans to support grpc calls? ?

**Comment by zesagata** [comment]
I see, tbh i'm not really sure what is need to be achieved. Currently if i need to call rpc endpoint, im using [BloomRPC](https://github.com/uw-labs/bloomrpc), and i think it would be nice if i can call rpc endpoint in `httpYAC` extension.

Anyway thanks for your response !

Im closing the issue

**Comment by AnWeber** [comment]
Do not close. I am already looking and thinking:-) I would have inspired me relatively freely [Insomania](https://support.insomnia.rest/article/188-grpc). But I still wanted to think about it, because I also want to implement Websocket (Stomp) and therefore it should be implemented generally if possible.

**Comment by stephsix** [comment]
In my humble opinion, RPC as an API Architectural Style, is [difference from REST and GraphQL](https://www.altexsoft.com/blog/soap-vs-rest-vs-graphql-vs-rpc/)：

- It is based on a variety of transport protocols(HTTP/1.1, HTTP/2, even UDP-based protocols)
- it requires some toolchains to generate **stub** and hacked into both sides of caller and callee
- the IDL is not universal, gRPC is restricted to proto3 while Dubbo(by Alibaba), Thrift(by Facebook), .NET WebService(by Microsoft) having their own implements.

So I think it is not a simple task for a REST-based tool to support most RPC Calls. But please feel free to think about gRPC, I'm very looking forward to call gRPC endpoint in `httpYAC` extension within simple configurations.

I'm working with a gRPC-liked framework using proto3 now, the best practice of mine is to providing RESTful interfaces along with RPC interfaces at the endpoint :)

**Comment by AnWeber** [comment]
@stephsix I agree with you that RPC calls are not possible in a REST-Based tool. But in principle httpyac only executes actions ([httpClient](https://github.com/AnWeber/httpyac/blob/main/src/actions/httpClientAction.ts#L10), [javascript](https://github.com/AnWeber/httpyac/blob/main/src/actions/javascriptAction.ts#L33)) that can have arbitrary content. My idea would be to basically define actions that allow the stub to be generated and then execute it. However, this code would be different for each RPC.

Using GRPC as an example, approximately the following NodeJS code would be required.
```js
const grpc = require('@grpc/grpc-js');
const protoLoader = require('@grpc/proto-loader');
const packageDefinition = protoLoader.loadSync('./grpc.proto';, loaderOptions);
const HelloService = grpc.loadPackageDefinition(packageDefinition).hello.HelloService;
const client = new HelloService( 'grpcb.in:9000', grpc.credentials.createInsecure());
client.sayHello({ greeting: 'test' }, (...args) => {
  ...
});
```

The following information in httpyac would be necessary:
```js
// protoImportAction
proto < ./grpc.proto

// grpcClientAction
GRPC grpcb.in:9000/hello.HelloService/sayHello
{
  "greetings": "text"
}
```
Over this scheme, one would subsequently need to lace a uniform construct for entry so that vscode-httpyac can determine which and how methods can be executed (request/response vs. streaming). The danger is that this scheme is too undefined and difficult to maintain/extend.

**Comment by AnWeber** [comment]
I would have provided gRPC support, however currently there is still an error in the proto import, but I did not have it during testing/debugging. I am still working on it.
```

**Comment by AnWeber** [comment]
Now the loading of the proto files also works. The reason was that Protobuf.js uses [require.resolve](https://stackoverflow.com/questions/57251875/webpack-use-nodes-require-resolve-instead-of-webpacks) internally. But since I use webpack as bundler and this transforms require calls, I unfortunately had the error. For this reason I have now switched to esbuild.
All 4 lifecyle of gRPC should now work (unary, server streaming, client streaming and bidi). I have implemented them using gRPCb.in. I am still in the process of writing a detailed [documentation](https://httpyac.github.io/guide/request.html#grpc).

```http
proto < ./hello.proto
proto < ./grpcbin.proto

@host=grpcb.in:9000

###

GRPC /hello.HelloService/sayHello
{
  "greeting": "world"
}

GRPC /hello.HelloService/LotsOfReplies
{
  "greeting": "world"
}


GRPC /hello.HelloService/lotsOfGreetings
{
  "greeting": "world."
}

{{@streaming

  async function writeStream(){
    sleep(1000);
    grpcStream.write({
      greeting: 'How are you?',
    });
    sleep(1000);
    grpcStream.write({
      greeting: 'I can stream.',
    });
  }
  exports.waitPromise = writeStream();
}}

GRPC /hello.HelloService/BidiHello
{
  "greeting": "world"
}

{{@streaming

  async function writeStream(){
    sleep(1000);
    grpcStream.write({
      greeting: ', how are you?',
    });
    sleep(1000);
    grpcStream.write({
      greeting: ', I can stream.',
    });
  }
  exports.waitPromise = writeStream();
}}


GRPC /grpcbin.GRPCBin/SpecificError
{
  "code": 4,
  "reason": "Meaning of life"
}
GRPC /grpcbin.GRPCBin/RandomError
{
  "fString": "bar"
}
GRPC /grpcbin.GRPCBin/HeadersUnary


GRPC /grpcbin.GRPCBin/NoResponseUnary
```

It would be great if someone would still look at it and possibly make suggestions for improvement. Please just create a new issue
