### ISSUE TITLE
Generate Code made a request

### ISSUE THREAD

**Issue by dragove** [AnWeber/vscode-httpyac#68]
extension version: `4.0.2`
vscodium version: `1.60.2`
Generate code won't make request in previous versions. In this version, it does.

**Comment by AnWeber** [comment]
As mentioned in #67, the change was implemented more for simplification. I will change it back to the original behavior.

**Comment by AnWeber** [comment]
I have provided an update with a fix.

Since the change was noticed so quickly, apparently the feature is more important to you. I added a few more improvements to code generation:
* new Setting `httpyac.generateCodeDefaultLanguage` to set default Language for Code Generation
* new Setting `httpyac.generateCodeTargetOutput` to specify Output Target of generated code (Clipboard or Window)
* new Command `httpyac.generateCodeSelectLanguage` to always select Language of Code Generation 
* CodeLens support for `httpyac.generateCode` and `httpyac.generateCodeSelectLanguage`
