### ISSUE TITLE
Use of .httpyac.json

### ISSUE THREAD

**Issue by asherber** [AnWeber/vscode-httpyac#71]
Really like some of the things you're doing with this extension!

I've got an .httpyac.json file that looks like this:

```json
{
    "environments": {
        "$shared": {
            "variables": {
                "host": "www.example.com"
            }
        }
    }
}
```

I've tried putting this file next to my .http file, in the workspace root, in the .vscode folder, and in the env folder -- but my .http file isn't picking up the `host` variable. Where is this file supposed to go?

(As a side note, it would be nice if I could hover over variables in the .http file to see the resolved value, or an error if the variable can't be found. Currently, I have to submit the request and see the resulting error to suss out any problems.)

**Comment by asherber** [comment]
Thanks, I appreciate the correction on the format of the file, and I'll wait for the bug fix to hit the released version.

Can you please clarify where I should be able to put the file? Is it the same locations as for .env?

**Comment by AnWeber** [comment]
> (As a side note, it would be nice if I could hover over variables in the .http file to see the resolved value, or an error if the variable can't be found. Currently, I have to submit the request and see the resulting error to suss out any problems.)

I've been thinking about this feature for a while, but I don't have an idea yet how to solve this without unreasonably high CPU and Memory consumption. The only way I can correctly determine all variables is to execute the request on every change in a http file. 

- Variables defined in Javascript. Scripts loaded by require can also set variables.
- References to other responses, because here the return type is not known
- Environment variables loaded from e.g. Spring Config Cloud or Hashicorp Vault, which are different depending on selected environment (maybe cachable?).

I do not want to include this function only so half ready. [vscode-restclient](https://github.com/Huachao/vscode-restclient/issues?q=is%3Aissue+performance+is%3Aclosed) tries to implement this feature and has as a consequence the performance problems.

As a solution I have currently built in that you can display the current variables (command `httpyac.showVariables`). I will wrap this soon in a [TreeDataProvider](https://code.visualstudio.com/api/extension-guides/tree-view#contributing-views-to-view-containers). I am open for good ideas.

**Comment by AnWeber** [comment]
I will add a CodeLens link für the command `httpyac.showVariables`. I would have thought of [CompletionItemProvider](https://code.visualstudio.com/api/references/vscode-api#CompletionItemProvider) (better IntelliSense) as well, but just haven't gotten around to it yet.

**Comment by AnWeber** [comment]
`showVariables` just shows the current state of the variables. No code is executed during this process. You can simply execute the request and then view the variables.
An alternative would be to install httpyac on the command line and view the variables using {{debugger;}} (see [docs](https://httpyac.github.io/guide/scripting.html#how-to-debug-scripts)).

I prevent the unexpected execution so explicitly, because I also create database entries in scripts, or combine writing services. However, in my cases I also have >80% of the variables in .env files and the remaining variables are generated in the same file, so it is easy for me to know the correct names. Do you dynamically create the variables in the NodeJs scripting part that it is difficult to know all the variable names present?

**Comment by AnWeber** [comment]
The command `httpyac.validateVariables` was rolled out with the new version.

**Comment by asherber** [comment]
Looks great, thanks!
